name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: "123456789:fake_token"
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
      REDIS_URL: "redis://localhost:6379"
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
